strip product bloat: Arch-only, zsh-only, rofi-only, single qs process
- Delete Fedora/openSUSE support (pre/post scripts, packages, grimblast)
- Strip multi-distro branching from 8 scripts (install-sddm, nvidia, snapshot, etc.)
- Remove bash/fish configs, keep only zsh
- Delete walker launcher and all walker references
- Merge quickshell overview + settings into main process (kill 2 extra qs)
- Delete unused hypr variants (38 animation/decoration/monitor/environment files)
- Remove full GTK4 settings app with meson/flatpak build system (apps/hyprland-settings)
- Delete dev tooling (debrand, sync, dotinst profiles)
- Remove update checker, CHANGELOG, CODE_OF_CONDUCT, YouTube links
- Fix hardcoded /home/raabe/ path, strip Dotfiles OS branding
- Update README for personal Arch-only setup

diff --git a/dotfiles/.config/dotfiles/scripts/change-shell b/dotfiles/.config/dotfiles/scripts/change-shell
--- a/dotfiles/.config/dotfiles/scripts/change-shell
+++ b/dotfiles/.config/dotfiles/scripts/change-shell
@@ -6,106 +6,31 @@
 # |____/|_| |_|\___|_|_|
 #
 
-sleep 1
+echo ":: Setting shell to zsh..."
 
-clear
-figlet -f smslant "Shell"
+while ! chsh -s $(which zsh); do
+    echo "ERROR: Authentication failed. Please enter the correct password."
+    sleep 1
+done
 
-echo ":: Please select your preferred shell"
-echo
-shell=$(gum choose "bash" "zsh" "fish" "Cancel")
-# -----------------------------------------------------
-# Activate bash
-# -----------------------------------------------------
-if [[ $shell == "bash" ]]; then
+echo ":: Shell is now zsh."
 
-    # Change shell to bash
-    while ! chsh -s $(which bash); do
-        echo "ERROR: Authentication failed. Please enter the correct password."
-        sleep 1
-    done
-    echo ":: Shell is now bash."
+if [ ! -d "$HOME/.oh-my-zsh" ]; then
+    echo ":: Installing oh-my-zsh"
+    sh -c "$(wget -O- https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)" "" --unattended
+fi
 
-    # Installing oh-my-posh
-    curl -s https://ohmyposh.dev/install.sh | bash -s
+if [ ! -d "$HOME/.oh-my-zsh/custom/plugins/zsh-autosuggestions" ]; then
+    echo ":: Installing zsh-autosuggestions"
+    git clone https://github.com/zsh-users/zsh-autosuggestions ${ZSH_CUSTOM:-$HOME/.oh-my-zsh/custom}/plugins/zsh-autosuggestions
+fi
 
-    gum spin --spinner dot --title "Please reboot your system." -- sleep 3
+if [ ! -d "$HOME/.oh-my-zsh/custom/plugins/zsh-syntax-highlighting" ]; then
+    echo ":: Installing zsh-syntax-highlighting"
+    git clone https://github.com/zsh-users/zsh-syntax-highlighting.git ${ZSH_CUSTOM:-$HOME/.oh-my-zsh/custom}/plugins/zsh-syntax-highlighting
+fi
 
-# -----------------------------------------------------
-# Activate fish
-# -----------------------------------------------------
-elif [[ $shell == "fish" ]]; then
-
-    echo ":: Please install fish manually for your distro (if not yet done) before proceeding."
-    if gum confirm "Is fish installed on your system?"; then
-
-        # Change shell to fish
-        while ! chsh -s $(which fish); do
-            echo "ERROR: Authentication failed. Please enter the correct password."
-            sleep 1
-        done
-        echo ":: Shell is now fish."
-
-        # Installing oh-my-posh
-        curl -s https://ohmyposh.dev/install.sh | bash -s
-
-        gum spin --spinner dot --title "Please reboot your system." -- sleep 3
-    fi
-
-# -----------------------------------------------------
-# Activate zsh
-# -----------------------------------------------------
-elif [[ $shell == "zsh" ]]; then
-
-    # Change shell to shh
-    while ! chsh -s $(which zsh); do
-        echo "ERROR: Authentication failed. Please enter the correct password."
-        sleep 1
-    done
-    echo ":: Shell is now zsh."
-
-    # Installing oh-my-posh
-    curl -s https://ohmyposh.dev/install.sh | bash -s
-
-    # Installing oh-my-zsh
-    if [ ! -d "$HOME/.oh-my-zsh" ]; then
-        echo ":: Installing oh-my-zsh"
-        sh -c "$(wget -O- https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)" "" --unattended
-        cp ~/.config/dotfiles/tpl/.zshrc ~/
-    else
-        echo ":: oh-my-zsh already installed"
-    fi
-
-    # Installing zsh-autosuggestions
-    if [ ! -d "$HOME/.oh-my-zsh/custom/plugins/zsh-autosuggestions" ]; then
-        echo ":: Installing zsh-autosuggestions"
-        git clone https://github.com/zsh-users/zsh-autosuggestions ${ZSH_CUSTOM:-$HOME/.oh-my-zsh/custom}/plugins/zsh-autosuggestions
-    else
-        echo ":: zsh-autosuggestions already installed"
-    fi
-
-    # Installing zsh-syntax-highlighting
-    if [ ! -d "$HOME/.oh-my-zsh/custom/plugins/zsh-syntax-highlighting" ]; then
-        echo ":: Installing zsh-syntax-highlighting"
-        git clone https://github.com/zsh-users/zsh-syntax-highlighting.git ${ZSH_CUSTOM:-$HOME/.oh-my-zsh/custom}/plugins/zsh-syntax-highlighting
-    else
-        echo ":: zsh-syntax-highlighting already installed"
-    fi
-
-    # Installing fast-syntax-highlighting
-    if [ ! -d "$HOME/.oh-my-zsh/custom/plugins/fast-syntax-highlighting" ]; then
-        echo ":: Installing fast-syntax-highlighting"
-        git clone https://github.com/zdharma-continuum/fast-syntax-highlighting.git ${ZSH_CUSTOM:-$HOME/.oh-my-zsh/custom}/plugins/fast-syntax-highlighting
-    else
-        echo ":: fast-syntax-highlighting already installed"
-    fi
-
-    gum spin --spinner dot --title "Please reboot your system." -- sleep 3
-
-# -----------------------------------------------------
-# Cencel
-# -----------------------------------------------------
-else
-    echo ":: Changing shell canceled"
-    exit
+if [ ! -d "$HOME/.oh-my-zsh/custom/plugins/fast-syntax-highlighting" ]; then
+    echo ":: Installing fast-syntax-highlighting"
+    git clone https://github.com/zdharma-continuum/fast-syntax-highlighting.git ${ZSH_CUSTOM:-$HOME/.oh-my-zsh/custom}/plugins/fast-syntax-highlighting
 fi
